databases:
  - name: dpg-chvjoqe4dad1r0bkul9g-a
    databaseName: budjet
    user: budjet

services:
  - type: web
    name: budjet2
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budjet
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false